### PR TITLE
Bump fast-chess and add opening book

### PR DESCRIPTION
**Pull request by bdmendes**

### CODE REVIEW

**Comment by Disservin** [comment]
mhh im looking at your ci right now and it seems that fast-chess doesnt finish the games near the end...? I am currently having a look if I can reproduce this

**Comment by bdmendes** [comment]
> mhh im looking at your ci right now and it seems that fast-chess doesnt finish the games near the end...? I am currently having a look if I can reproduce this

Yes, it seems that it never finishes. It worked fine on v0.4-alpha. I can't reproduce locally, though

**Comment by Disservin** [comment]
Mhh okay I came across a few bugs in fast-chess, which could have caused a crash under certain circumstances. Though I'm not sure if it fixes your CI, since in both cases it never finishes near the end... and if fast-chess would crash I would also expect the ci to fail? Idk. I'd say update your ci tag to `v0.6.1-alpha` and we will see.

**Comment by Disservin** [comment]
Ah I also forgot to mention that uci actually says that the engine should send a last `info` before the bestmove. Some issue's were related to the fact that your engine in some cases only ever send `bestmove ...` without the last info line, could happen if your engine has very little time left. (but I should have probably not relied on the fact that everyone does this).

**Pull request merged**
