### PR TITLE
Remove check extension

### PR DESCRIPTION
**Pull request by bdmendes**

### CODE REVIEW

**Comment by tissatussa** [comment]
this may be a solution to #73 ?

**Comment by bdmendes** [comment]
@tissatussa I would say #77 is a better candidate for fixing that bug, but I have not managed to reproduce it. Can you check it?

**Comment by tissatussa** [comment]
> @tissatussa I would say #77 is a better candidate for fixing that bug, but I have not managed to reproduce it. Can you check it?

you mean, i shall `git clone` and compile the newest source and then test the concerning #73 FEN ? I can try..

**Comment by bdmendes** [comment]
Yes, although I am not sure you will be able to reproduce it without the entire game sequence

**Comment by tissatussa** [comment]
> Yes, although I am not sure you will be able to reproduce it without the entire game sequence

with the older Camel 1.1.0 i just tried the same FEN of #73 (the position after 52...Kh3 in that game) with the same settings (time and opponent) and Camel instantly mated in 3 moves .. so, i guess during the #73 game "the entire game sequence" filled the TT / Hash with wrong data (to put it simply) and my new try didn't have that data .. so, if you ask "Can you check it?" the answer is No .. isn't it ? I didn't try a newest compile yet ..

**Comment by bdmendes** [comment]
Well in 1.1.0 the hashing was random, it is now predictable since I am using a fixed seed. So while it is hard to reproduce collision bugs in the oldest versions, it should now be easier to identify future bugs.

**Comment by bdmendes** [comment]
If you cannot reproduce the issue, make sure to close it, and feel free to open new ones if you find them!

**Pull request closed without merging**
